// ==========================================================================
// JS/STUDENT-FORM.JS - Add and Edit Student Form Controller
// ==========================================================================

let isEditMode = false;
let currentStudentId = null;

document.addEventListener('DOMContentLoaded', async () => {
  const user = Auth.requireRole('admin');
  if (!user) return;

  Common.initSidebar();
  await loadCoursesDropdown();

  const urlParams = new URLSearchParams(window.location.search);
  currentStudentId = urlParams.get('id');

  if (currentStudentId) {
    isEditMode = true;
    document.getElementById('pageTitle').textContent = 'Edit Student';
    document.getElementById('pageSubtitle').textContent = `Update information for student ${currentStudentId}`;
    document.getElementById('submitBtnText').textContent = 'Update Student';
    await loadStudentForEditing(currentStudentId);
  } else {
    // Add mode: default admission date to today
    const admInput = document.getElementById('admissionDate');
    if (admInput) admInput.value = new Date().toISOString().split('T')[0];
  }

  // Handle Form Submit
  const form = document.getElementById('studentForm');
  if (form) {
    form.addEventListener('submit', handleStudentFormSubmit);
  }
});

async function loadCoursesDropdown() {
  const select = document.getElementById('course');
  if (!select) return;

  try {
    const res = await api.getCourses();
    if (res && res.status === 'success' && res.courses) {
      res.courses.forEach(c => {
        const opt = document.createElement('option');
        opt.value = c.name;
        opt.textContent = c.name;
        select.appendChild(opt);
      });
    }
  } catch (err) {
    console.error('Failed to load courses:', err);
  }
}

async function loadStudentForEditing(studentId) {
  try {
    const res = await api.getStudent(studentId);
    if (res && res.status === 'success' && res.student) {
      const s = res.student;
      document.getElementById('studentId').value = s.studentId;
      document.getElementById('firstName').value = s.firstName || '';
      document.getElementById('lastName').value = s.lastName || '';
      document.getElementById('admissionDate').value = s.admissionDate || '';
      document.getElementById('dob').value = s.dob || '';
      document.getElementById('gender').value = s.gender || '';
      document.getElementById('course').value = s.course || '';
      document.getElementById('status').value = s.status || 'Active';
      document.getElementById('email').value = s.email || '';
      document.getElementById('phone').value = s.phone || '';
      document.getElementById('address').value = s.address || '';
    } else {
      Common.showToast('Student record not found.', 'error');
      setTimeout(() => window.location.href = 'index.html', 1500);
    }
  } catch (err) {
    console.error('Error loading student for edit:', err);
    Common.showToast('Failed to load student details for editing.', 'error');
  }
}

async function handleStudentFormSubmit(event) {
  event.preventDefault();

  const submitBtn = document.getElementById('submitBtn');
  submitBtn.disabled = true;
  submitBtn.innerHTML = `<i class="ri-loader-4-line" style="animation: spin 1s infinite linear;"></i> Saving...`;

  const payload = {
    firstName: document.getElementById('firstName').value.trim(),
    lastName: document.getElementById('lastName').value.trim(),
    admissionDate: document.getElementById('admissionDate').value,
    dob: document.getElementById('dob').value,
    gender: document.getElementById('gender').value,
    course: document.getElementById('course').value,
    status: document.getElementById('status').value,
    email: document.getElementById('email').value.trim(),
    phone: document.getElementById('phone').value.trim(),
    address: document.getElementById('address').value.trim()
  };

  try {
    let res;
    if (isEditMode) {
      res = await api.updateStudent(currentStudentId, payload);
    } else {
      // Automatic Student ID generated by backend!
      payload.password = '123456'; // Default initial password
      res = await api.addStudent(payload);
    }

    if (res && (res.status === 'success' || res.status === 200 || res.status === 201)) {
      Common.showToast(res.message || 'Student saved successfully!', 'success');
      setTimeout(() => {
        window.location.href = 'index.html';
      }, 1200);
    } else {
      Common.showToast(res.message || 'Operation failed. Please check your inputs.', 'error');
      submitBtn.disabled = false;
      submitBtn.innerHTML = `<i class="ri-save-line"></i> <span id="submitBtnText">${isEditMode ? 'Update Student' : 'Save Student'}</span>`;
    }
  } catch (err) {
    console.error('Submit error:', err);
    Common.showToast('Server communication error. Please try again.', 'error');
    submitBtn.disabled = false;
    submitBtn.innerHTML = `<i class="ri-save-line"></i> <span id="submitBtnText">${isEditMode ? 'Update Student' : 'Save Student'}</span>`;
  }
}
